#page title
page_title                                : ç•ªèŒ„OKR                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1609740590                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : cn                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : http://yuanzhixu.com/                                       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : å‘¨æœŸOKR                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : å…è´¹                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : æä¾›æœ€å…ˆè¿›çš„ç”Ÿäº§åŠ›

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : å…ƒç§©åº ğŸª æ•°å­—ç§‘æŠ€æœ‰é™å…¬å¸                        
your_link                                 : http://yuanzhixu.com/    
your_city                                 :         
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :


  - title                                 : æœ€å…ˆè¿›çš„æ•ˆç‡å“²å­¦
    description                           : ç”¨ç¡…è°·æœ€æ–°çš„æ•ˆç‡å·¥å…·OKRç®¡ç†ç›®æ ‡,ç”¨ç•ªèŒ„å·¥ä½œæ³•å°†ç›®æ ‡è½å®åˆ°æ‰§è¡Œ
    fontawesome_icon_name                 : fa-solid fa-shuttle-space

  - title                                 : IOSå…¨å¹³å°
    description                           : APPè¦†ç›– IPhone,IPad,macOS,å…¨å¹³å°æ”¯æŒè‹¹æœè®¾å¤‡
    fontawesome_icon_name                 : fa-brands fa-apple
    
  - title                                 : äº‘å­˜å‚¨
    description                           : æ•°æ®äº‘å­˜å‚¨ï¼Œæ— éœ€å¤‡ä»½ï¼Œä¸æ€•ä¸¢å¤±ï¼ŒIOSå…¨å¹³å°æ‰€æœ‰è®¾å¤‡æ—¶åˆ»ä¿æŒåŒæ­¥
    fontawesome_icon_name                 : fa-solid fa-cloud

  - title                                 : OKR
    description                           : é«˜æ•ˆçš„ç›®æ ‡ç®¡ç†æ–¹æ³•ï¼Œç”±Googleå‘æ‰¬å…‰å¤§ï¼Œè¢«å›½å†…äº’è”ç½‘å…¬å¸æ‰€æ¨å´‡ä½¿ç”¨
    fontawesome_icon_name                 : fa-solid fa-bullseye

  - title                                 : ç•ªèŒ„å·¥ä½œæ³•
    description                           : ç®€å•æ˜“è¡Œçš„æ—¶é—´ç®¡ç†æ–¹æ³•ï¼Œè®©è‡ªå·±æœ€å¥½çš„ç²¾åŠ›å…¨æƒ…æŠ•å…¥
    fontawesome_icon_name                 : fa-solid fa-clock

  - title                                 : ä»£åŠäº‹é¡¹
    description                           : OKRçš„åˆ¶å®šåï¼Œéœ€è¦å°†å…¶åˆ†è§£æˆæ¯ä¸ªåˆ‡å®å¯è¡Œçš„å°äº‹é¡¹ã€‚
    fontawesome_icon_name                 : fa-solid fa-square-check

  - title                                 : ç™½å™ªå£°
    description                           : æä¾›å¤šåœºæ™¯ç™½å™ªå£°,è®©å·¥ä½œå¦‚åŒç½®èº«äºè‡ªç„¶
    fontawesome_icon_name                 : fa-solid fa-headphones

  - title                                 : å¤šç§å›¾è¡¨
    description                           : åŒ…å«é¥¼å›¾ï¼ŒæŸ±çŠ¶å›¾ï¼Œæ—¶é—´çº¿å›¾ç­‰ã€‚æ–¹ä¾¿æŸ¥çœ‹è‡ªå·±å–å¾—çš„æˆæœå’Œå¤ç›˜ã€‚
    fontawesome_icon_name                 : fa-solid fa-chart-simple

  - title                                 : æ—¶é—´å‘¨æœŸ
    description                           : å®ç°OKRçš„è¿‡ç¨‹é‡Œï¼Œé…å¤‡å‘¨æœŸè¿›åº¦ï¼Œæ›´å¥½æŠŠæ¡ç›®æ ‡çš„æ‰§è¡Œï¼Œä¸ä»…çŸ¥é“æˆ‘ä»¬è¦å»å“ªï¼Œè¿˜èƒ½æ—¶åˆ»çŸ¥é“æˆ‘ä»¬åœ¨å“ª
    fontawesome_icon_name                 : fa-solid fa-clock-rotate-left




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site

exclude:
  - vendor
  - LICENSE
  - README.md
  - CNAME



collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
